### ISSUE TITLE
how do i get the pink icon?

### ISSUE THREAD

**Issue by rikohabib** [Trollwut/gtk-theme-trollwut-pink-dark#1]
does this included with the icon pack? where is it? thanks. Anyway, great job!

**Comment by Trollwut** [comment]
Those were the Numix folders. So you need Numix icon theme, then use this script: https://github.com/numixproject/numix-folders

It's pretty self-explanatory, use the pink color. :)

Nowadays I use "Tela" icon theme, which also have a pink one, you might want to look at them, too.

Hope I could help! If not, don't hesitate to ask.
